server:
  port: 8050
spring:
  application:
    name: account
  datasource:
    name: springclouddiancan
    url: jdbc:mysql://localhost:3306/springclouddiancan?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wang
eureka:
  client:
    servict-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.southwind.entity

