server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: springclouddiancan
    url: jdbc:mysql://localhost:3306/springclouddiancan
    username: root
    password: wang
eureka:
  client:
    servict-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true